language: python
python:
  - '3.5'
install: true
script:
  - python3 travis/sqf_validator.py
  - python3 travis/config_style_checker.py
notifications:
  email:
    on_success: never
    on_failure: change